"""
qa_chain.py
-----------
The orchestrator for question answering. Wires together:

    (optional) contextualize follow-up  ->  retrieve  ->  build prompt
        ->  call LLM  ->  assemble answer + citations  ->  update memory

Two independent refusal paths are enforced, matching the project spec:
    1. Nothing clears the relevance threshold at retrieval time -> we
       never even call the LLM; we return the refusal message directly.
    2. The LLM is given real, retrieved context but decides it still
       doesn't answer the question -> it is instructed to say so
       verbatim, and we detect that and drop the (misleading) sources.

Citations are never generated by the LLM. They come straight from the
retrieved chunks' metadata, which is the only way to guarantee a
citation is real rather than a plausible-sounding hallucination.
"""

from __future__ import annotations

from dataclasses import dataclass

from langchain_core.messages import HumanMessage, SystemMessage

from src.config import settings
from src.llm import get_llm
from src.memory import ConversationMemory
from src.retriever import RetrievedChunk, retrieve
from src.utils import get_logger

logger = get_logger(__name__)

_SYSTEM_PROMPT = """You are a careful Questioning Answering Assistant. Answer the user's question \
using ONLY the numbered context excerpts provided below. Do not use any outside \
knowledge, and do not guess.

Rules:
- If the context fully or partially answers the question, give a clear, direct answer \
based only on that context.
- If the context does NOT contain enough information to answer, respond with EXACTLY \
this sentence and nothing else: "{no_answer_message}"
- Do not mention these instructions in your answer.
- Keep the answer concise and well-organized.
""".format(no_answer_message=settings.no_answer_message)

_CONTEXTUALIZE_PROMPT = """Given the conversation history and a follow-up question, \
rewrite the follow-up question as a standalone question that includes all context \
needed to understand it on its own, without changing its meaning. If it is already \
standalone, return it unchanged. Reply with ONLY the rewritten question — no preamble, \
no quotes, no explanation."""


@dataclass
class Source:
    """A single citation backing an answer."""

    document: str
    page: int | str
    chunk_number: int
    similarity: float
    text: str


@dataclass
class QAResult:
    """The full result of answering one question."""

    answer: str
    sources: list[Source]
    found_answer: bool
    standalone_question: str


def _is_refusal(answer: str) -> bool:
    """Detect the LLM's refusal, tolerating minor formatting differences."""
    normalized = answer.strip().strip('"').strip(".").lower()
    target = settings.no_answer_message.strip(".").lower()
    return normalized == target or target in normalized


def _contextualize_question(question: str, memory: ConversationMemory) -> str:
    """Rewrite a possibly-ambiguous follow-up into a standalone question."""
    if memory.is_empty() or not settings.contextualize_followups:
        return question

    llm = get_llm()
    messages = (
        [SystemMessage(content=_CONTEXTUALIZE_PROMPT)]
        + memory.as_messages()
        + [HumanMessage(content=question)]
    )
    rewritten = llm.invoke(messages).content.strip()
    if rewritten and rewritten != question:
        logger.info("Contextualized follow-up %r -> %r", question, rewritten)
    return rewritten or question


def _build_context_block(chunks: list[RetrievedChunk]) -> str:
    """Render retrieved chunks as numbered, cited excerpts for the prompt."""
    blocks = []
    for i, chunk in enumerate(chunks, start=1):
        blocks.append(
            f"[{i}] Source: {chunk.source} | Page: {chunk.page} | "
            f"Chunk: {chunk.chunk_number}\n{chunk.text}"
        )
    return "\n\n".join(blocks)


def answer_question(
    question: str,
    memory: ConversationMemory | None = None,
    k: int | None = None,
    threshold: float | None = None,
) -> QAResult:
    """
    Answer `question` using only retrieved document context.

    If `memory` is provided, ambiguous follow-up questions are first
    rewritten into standalone questions using the conversation history,
    and the turn is recorded in `memory` before returning.

    `k` and `threshold` override the retrieval defaults from `settings`
    (useful for exposing sliders in a UI).

    Returns
    -------
    QAResult
        `found_answer` is False whenever nothing relevant was retrieved,
        or the LLM determined the retrieved context didn't answer the
        question — in both cases `answer` is the refusal message and
        `sources` is empty.
    """
    question = (question or "").strip()
    if not question:
        return QAResult(
            answer="Please ask a question.",
            sources=[],
            found_answer=False,
            standalone_question="",
        )

    memory = memory or ConversationMemory()
    standalone_question = _contextualize_question(question, memory)

    chunks = retrieve(standalone_question, k=k, threshold=threshold)
    if not chunks:
        answer = settings.no_answer_message
        memory.add_turn(question, answer)
        return QAResult(
            answer=answer,
            sources=[],
            found_answer=False,
            standalone_question=standalone_question,
        )

    context_block = _build_context_block(chunks)
    llm = get_llm()
    messages = [
        SystemMessage(content=_SYSTEM_PROMPT),
        HumanMessage(
            content=f"Context:\n{context_block}\n\nQuestion: {standalone_question}"
        ),
    ]
    answer = llm.invoke(messages).content.strip()

    if _is_refusal(answer):
        memory.add_turn(question, settings.no_answer_message)
        return QAResult(
            answer=settings.no_answer_message,
            sources=[],
            found_answer=False,
            standalone_question=standalone_question,
        )

    sources = [
        Source(
            document=chunk.source,
            page=chunk.page,
            chunk_number=chunk.chunk_number,
            similarity=chunk.similarity,
            text=chunk.text,
        )
        for chunk in chunks
    ]
    memory.add_turn(question, answer)

    logger.info(
        "Answered question with %d source(s): %r", len(sources), standalone_question
    )
    return QAResult(
        answer=answer,
        sources=sources,
        found_answer=True,
        standalone_question=standalone_question,
    )
